# Test your FastAPI endpoints

###

GET http://127.0.0.1:8000/emdb/emd-1832/box/0/0/0/1/1/1/100
Accept: application/json

> {%
client.test("Check body", function() {
  const expectedStatus = 200;
  client.log(`Received ${response.status} with body ${response.body}`)
  client.assert(response.status === expectedStatus,  `Expected ${expectedStatus} status but received ${response.status}`);
});

%}

###

GET http://127.0.0.1:8000/emdb/emd-1832/metadata
Accept: application/json

> {%
client.test("Check body", function() {
  const expectedStatus = 200;
  client.log(`Received ${response.status} with body ${response.body}`)
  client.assert(response.status === expectedStatus,  `Expected ${expectedStatus} status but received ${response.status}`);
});

%}